# Generated by Django 5.2.14 on 2026-05-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='title_ja',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
