# Generated by Django 5.2.14 on 2026-05-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvoice', '0002_newsarticle_title_ja'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tts_provider', models.CharField(choices=[('openai', 'OpenAI TTS'), ('google', 'Google Cloud TTS'), ('voicevox', 'VOICEVOX'), ('other', 'Other')], max_length=50)),
                ('voice_name', models.CharField(blank=True, max_length=100)),
                ('audio_file', models.FileField(blank=True, upload_to='newsvoice/audio/')),
                ('audio_format', models.CharField(default='mp3', max_length=20)),
                ('script_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='newsvoice.newssummary')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tts_provider', 'voice_name', 'script_hash'], name='newsvoice_n_tts_pro_5051f7_idx')],
            },
        ),
    ]
