# Generated by Django 5.2.14 on 2026-05-13 11:25

import django.db.models.deletion
import newsvoice.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvoice', '0006_processingjob_article_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=newsvoice.models.generate_two_factor_code, max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsvoice_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User two-factor code',
                'verbose_name_plural': 'User two-factor codes',
            },
        ),
        migrations.RenameIndex(
            model_name='processingjob',
            new_name='newsvoice_p_status_067323_idx',
            old_name='newsvoice_p_status_78df08_idx',
        ),
    ]
