# Generated by Django 5.2.14 on 2026-05-13 11:31

import newsvoice.services.totp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvoice', '0007_usertwofactorcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertwofactorcode',
            name='code',
        ),
        migrations.AddField(
            model_name='usertwofactorcode',
            name='secret',
            field=models.CharField(default=newsvoice.services.totp.generate_totp_secret, max_length=64),
        ),
    ]
