# Generated by Django 5.2.14 on 2026-05-13 11:50

from django.db import migrations, models


def get_default_username(apps):
    User = apps.get_model("auth", "User")
    user = User.objects.filter(is_superuser=True).order_by("id").first() or User.objects.order_by("id").first()
    return user.username if user else "admin"


def backfill_usernames(apps, schema_editor):
    NewsArticle = apps.get_model("newsvoice", "NewsArticle")
    NewsSummary = apps.get_model("newsvoice", "NewsSummary")
    NewsAudio = apps.get_model("newsvoice", "NewsAudio")
    ProcessingJob = apps.get_model("newsvoice", "ProcessingJob")
    UserTwoFactorCode = apps.get_model("newsvoice", "UserTwoFactorCode")

    default_username = get_default_username(apps)
    NewsArticle.objects.filter(username="").update(username=default_username)

    for summary in NewsSummary.objects.select_related("article").filter(username=""):
        summary.username = summary.article.username or default_username
        summary.save(update_fields=["username"])

    for audio in NewsAudio.objects.select_related("summary").filter(username=""):
        audio.username = audio.summary.username or default_username
        audio.save(update_fields=["username"])

    for job in ProcessingJob.objects.select_related("article").filter(username=""):
        job.username = job.article.username or default_username
        job.save(update_fields=["username"])

    for user_code in UserTwoFactorCode.objects.select_related("user").filter(username=""):
        user_code.username = user_code.user.username
        user_code.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ('newsvoice', '0008_rename_newsvoice_p_status_78df08_idx_newsvoice_p_status_067323_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='newssummary',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='processingjob',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='usertwofactorcode',
            name='username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.RunPython(backfill_usernames, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(),
        ),
        migrations.AddIndex(
            model_name='newsaudio',
            index=models.Index(fields=['username', 'status', 'updated_at'], name='newsvoice_n_usernam_473309_idx'),
        ),
        migrations.AddIndex(
            model_name='processingjob',
            index=models.Index(fields=['username', 'status', 'job_type', 'created_at'], name='newsvoice_p_usernam_15ba06_idx'),
        ),
        migrations.AddConstraint(
            model_name='newsarticle',
            constraint=models.UniqueConstraint(fields=('username', 'url'), name='newsvoice_article_username_url_uniq'),
        ),
    ]
