# Generated by Django 5.2.14 on 2026-05-13 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsvoice', '0009_newsarticle_username_newsaudio_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElevenLabsVoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default='', max_length=150)),
                ('voice_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('preview_url', models.URLField(blank=True)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('samples', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NewsVoiceTTSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('provider', models.CharField(default='elevenlabs', max_length=50)),
                ('model_id', models.CharField(default='eleven_multilingual_v2', max_length=100)),
                ('output_format', models.CharField(default='mp3_44100_128', max_length=50)),
                ('language_code', models.CharField(default='ja', max_length=10)),
                ('stability', models.FloatField(default=0.45)),
                ('similarity_boost', models.FloatField(default=0.75)),
                ('style', models.FloatField(default=0.2)),
                ('speed', models.FloatField(default=0.95)),
                ('use_speaker_boost', models.BooleanField(default=True)),
                ('attribution_text', models.CharField(default='Voice generated with ElevenLabs.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='language_code',
            field=models.CharField(default='ja', max_length=10),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='model_id',
            field=models.CharField(default='eleven_multilingual_v2', max_length=100),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='output_format',
            field=models.CharField(default='mp3_44100_128', max_length=50),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='similarity_boost',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='speed',
            field=models.FloatField(default=0.95),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='stability',
            field=models.FloatField(default=0.45),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='style',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='use_speaker_boost',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsaudio',
            name='voice_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newsaudio',
            name='tts_provider',
            field=models.CharField(choices=[('elevenlabs', 'ElevenLabs'), ('openai', 'OpenAI TTS'), ('google', 'Google Cloud TTS'), ('voicevox', 'VOICEVOX'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='newsaudio',
            index=models.Index(fields=['username', 'tts_provider', 'voice_id', 'model_id', 'output_format', 'script_hash'], name='newsvoice_n_usernam_77d3e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='elevenlabsvoice',
            constraint=models.UniqueConstraint(fields=('username', 'voice_id'), name='newsvoice_eleven_voice_user_voice_uniq'),
        ),
        migrations.AddField(
            model_name='newsvoicettssetting',
            name='default_voice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsvoice.elevenlabsvoice'),
        ),
    ]
