from .settings import *

DEBUG = False
SECRET_KEY = "REPLACE_ME"
ALLOWED_HOSTS = [
    "newsvoice.simoyakaviewer.com",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True

GEMINI_API_KEY = "REPLACE_ME"
GEMINI_MODEL = "gemini-2.5-flash-lite"

NEWSVOICE_SIMPLE_TTS_ENABLED = True
NEWSVOICE_HIGH_QUALITY_TTS_ENABLED = True
NEWSVOICE_DEFAULT_TTS_PROVIDER = "elevenlabs"
NEWSVOICE_DEFAULT_VOICE_NAME = ""

ELEVENLABS_API_KEY = "REPLACE_ME"
ELEVENLABS_DEFAULT_MODEL_ID = "eleven_multilingual_v2"
ELEVENLABS_DEFAULT_OUTPUT_FORMAT = "mp3_44100_128"
ELEVENLABS_DEFAULT_LANGUAGE_CODE = "ja"
ELEVENLABS_DEFAULT_STABILITY = 0.45
ELEVENLABS_DEFAULT_SIMILARITY_BOOST = 0.75
ELEVENLABS_DEFAULT_STYLE = 0.20
ELEVENLABS_DEFAULT_SPEED = 0.95
ELEVENLABS_DEFAULT_USE_SPEAKER_BOOST = True
