GEMINI_API_KEY = "your-api-key"
GEMINI_MODEL = "gemini-2.5-flash-lite"

NEWSVOICE_SIMPLE_TTS_ENABLED = True
NEWSVOICE_HIGH_QUALITY_TTS_ENABLED = False
NEWSVOICE_DEFAULT_TTS_PROVIDER = "voicevox"
NEWSVOICE_DEFAULT_VOICE_NAME = ""
